name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '24 */24 * * *'  # Once a day

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: true
          enable_jekyll: true
          cname: damien.co


name: HugoTest

on:
  push:
    branches:
      - master
      
 jobs:
  deploy:
    runs-on: ubuntu-18.04    
      steps:
        - uses: peaceiris/actions-hugo-link-check@v0.56.3
        - name: -  "hugo-link-check" {
          with:
          HUGO_OPTIONS = "--buildDrafts"
          OPTIONS = "-e 'http://localhost:8000'"
