name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@v1.0.0
      with:
        # Required:
        url: 'http://damien.co'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: 'github,google,linkedin'
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
